# Generated by Django 4.0.4 on 2022-06-18 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_otp_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pan',
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'Pan')], default='AADHAAR', max_length=100)),
                ('type_id', models.CharField(blank=True, max_length=12, null=True)),
                ('reference_id', models.CharField(max_length=75, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'kyc',
                'verbose_name_plural': "kyc's",
                'db_table': 'users_kyc',
            },
        ),
    ]
